source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YHImageViewer_Example', :exclusive => true do
  pod "YHImageViewer", :path => "../"
end

target 'YHImageViewer_Tests', :exclusive => true do
  pod "YHImageViewer", :path => "../"

  
end
